#!/bin/bash

if [[ ! -z $1 ]]; then
	PORT=$1
else
	PORT=4000
fi

docker pull mrseccubus/github-pages:latest
if [[ $(uname -a|grep -i microsoft|wc -l) -gt 0 ]]; then
	IP=$(ip addr show eth0 |grep "inet "|awk '{ print $2 }'|sed 's/\/.*$//')
	echo "*******************************************************************************************"
	echo "On WSL2 the docker container is reachable via this url: http://$IP:$PORT"
	echo "*******************************************************************************************"
fi
docker run \
	--volume="$PWD/../:/root/project:delegated" \
	--entrypoint /bin/bash \
	--publish $PORT:4000 \
	-ti mrseccubus/github-pages \
	-c "
		gem install jekyll-secinfo jekyll-paginate;
		cd /root/project/www.divd.nl;
		while [ 1 ] ; do
			./update.sh
			rm -rf _site/*;
			jekyll serve --incremental --host=0.0.0.0 --future 2>&1 |grep -Ev 'rb:[0-9]+: warning'
			set -e
			echo 'Press CTRL+C now to quit'
			sleep 1
			set +e
			echo 'Restarting...'
		done
	"
