#!/bin/bash

if [[ ! -z $1 ]]; then
	PORT=$1
else
	PORT=4000
fi

docker pull mrseccubus/github-pages:latest
if [[ $(uname -a|grep -i microsoft|wc -l) -gt 0 ]]; then
	IP=$(ip addr show eth0 |grep "inet "|awk '{ print $2 }'|sed 's/\/.*$//')
	echo "*******************************************************************************************"
	echo "On WSL2 the docker container is reachable via this url: http://$IP:$PORT"
	echo "*******************************************************************************************"
	export URL="http://$IP:$PORT"
fi
./update.sh
docker run \
	--volume="$PWD:/srv/jekyll:delegated" \
	--entrypoint /bin/bash \
	--publish $PORT:4000 \
	--env URL="$URL" \
	-ti mrseccubus/github-pages \
	-c "
		echo 'Running bundle install (be patient...)';
		bundle install --jobs=2;
		while [ 1 ] ; do
			rm -rf _site/*;
			if [[ "$URL" != "" ]]; then
				echo \"*** Site URL: $URL\"
			fi
			bundle exec jekyll serve --incremental --host=0.0.0.0 --future 2>&1
			set -e
			echo 'Press CTRL+C now to quit'
			sleep 1
			set +e
			echo 'Restarting...'
		done
	"
